// Date: 17/11/2014 12:09:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.robowars.core.client.model.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBotShoot extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer neck;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer armjointright;
    ModelRenderer armjointleft;
    ModelRenderer armright;
    ModelRenderer armleft;
    ModelRenderer weaponhand;
    ModelRenderer weaponbarrel;
    ModelRenderer hover1;
    ModelRenderer hover2;
    ModelRenderer hover3;
  
  public ModelBotShoot()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 35, 0);
      head.addBox(-2.5F, -5F, -5F, 5, 5, 8);
      head.setRotationPoint(0.5F, -2.7F, 1F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 0, 37);
      neck.addBox(-2F, 0F, -2F, 3, 3, 4);
      neck.setRotationPoint(1F, -4F, 1F);
      neck.setTextureSize(64, 32);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      body1 = new ModelRenderer(this, 0, 0);
      body1.addBox(-3.5F, 0F, -4F, 8, 9, 7);
      body1.setRotationPoint(0F, -1.5F, 1F);
      body1.setTextureSize(64, 32);
      body1.mirror = true;
      setRotation(body1, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 0, 19);
      body2.addBox(-4F, 0F, -5F, 10, 7, 9);
      body2.setRotationPoint(-0.5F, -1F, 1F);
      body2.setTextureSize(64, 32);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 0, 45);
      body3.addBox(-4F, 0F, -2F, 5, 10, 4);
      body3.setRotationPoint(2F, 3.5F, 2F);
      body3.setTextureSize(64, 32);
      body3.mirror = true;
      setRotation(body3, -0.2094395F, 0F, 0F);
      armjointright = new ModelRenderer(this, 15, 38);
      armjointright.addBox(0F, -1F, -1F, 2, 2, 2);
      armjointright.setRotationPoint(-6.5F, 1.5F, 1F);
      armjointright.setTextureSize(64, 32);
      armjointright.mirror = true;
      setRotation(armjointright, 0F, 0F, 0F);
      armjointleft = new ModelRenderer(this, 15, 38);
      armjointleft.addBox(-1F, -1F, -1F, 2, 2, 2);
      armjointleft.setRotationPoint(6.5F, 1.5F, 1F);
      armjointleft.setTextureSize(64, 32);
      armjointleft.mirror = true;
      setRotation(armjointleft, 0F, 0F, 0F);
      armright = new ModelRenderer(this, 63, 0);
      armright.addBox(-2F, -2F, -1.5F, 2, 8, 3);
      armright.setRotationPoint(-5.5F, 1.5F, 1F);
      armright.setTextureSize(64, 32);
      armright.mirror = true;
      setRotation(armright, -0.6108652F, 0F, 0F);
      armleft = new ModelRenderer(this, 63, 13);
      armleft.addBox(0F, -2F, -1.5F, 2, 12, 3);
      armleft.setRotationPoint(6.5F, 1.5F, 1F);
      armleft.setTextureSize(64, 32);
      armleft.mirror = true;
      setRotation(armleft, 0F, 0F, 0F);
      weaponhand = new ModelRenderer(this, 39, 15);
      weaponhand.addBox(-1F, 0F, -2F, 3, 7, 4);
      weaponhand.setRotationPoint(-7F, 6.5F, -1F);
      weaponhand.setTextureSize(64, 32);
      weaponhand.mirror = true;
      setRotation(weaponhand, -1.570796F, 0F, 0F);
      weaponbarrel = new ModelRenderer(this, 39, 27);
      weaponbarrel.addBox(-0.5F, 6F, -1.5F, 2, 3, 3);
      weaponbarrel.setRotationPoint(-7F, 6.5F, -1F);
      weaponbarrel.setTextureSize(64, 32);
      weaponbarrel.mirror = true;
      setRotation(weaponbarrel, -1.570796F, 0F, 0F);
      hover1 = new ModelRenderer(this, 61, 36);
      hover1.addBox(-3.5F, 0F, -4F, 8, 2, 6);
      hover1.setRotationPoint(0F, 12.5F, 1F);
      hover1.setTextureSize(64, 32);
      hover1.mirror = true;
      setRotation(hover1, 0F, 0F, 0F);
      hover2 = new ModelRenderer(this, 24, 38);
      hover2.addBox(-4F, 0F, -4F, 9, 5, 7);
      hover2.setRotationPoint(0F, 13F, 0.5F);
      hover2.setTextureSize(64, 32);
      hover2.mirror = true;
      setRotation(hover2, 0F, 0F, 0F);
      hover3 = new ModelRenderer(this, 61, 46);
      hover3.addBox(-3.5F, 0F, -4F, 8, 2, 6);
      hover3.setRotationPoint(0F, 16.5F, 1F);
      hover3.setTextureSize(64, 32);
      hover3.mirror = true;
      setRotation(hover3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    neck.render(f5);
    body1.render(f5);
    body2.render(f5);
    body3.render(f5);
    armjointright.render(f5);
    armjointleft.render(f5);
    armright.render(f5);
    armleft.render(f5);
    weaponhand.render(f5);
    weaponbarrel.render(f5);
    hover1.render(f5);
    hover2.render(f5);
    hover3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
