// Date: 17/11/2014 11:31:53 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.robowars.core.client.model.entity;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import com.robowars.core.client.renderer.entity.monster.RenderBot.ModelBaseBot;

public class ModelHeavyBotMelee extends ModelBaseBot
{
    //fields
    ModelRenderer head;
    ModelRenderer neck;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer armjointleft;
    ModelRenderer armjointright;
    ModelRenderer armleft;
    ModelRenderer armright;
    ModelRenderer armhandright;
    ModelRenderer armhandleft;
    ModelRenderer hover1;
    ModelRenderer hover2;
    ModelRenderer hover3;

    public ModelHeavyBotMelee()
    {
        textureWidth = 128;
        textureHeight = 64;

        head = new ModelRenderer(this, 35, 0);
        head.addBox(-3F, -8F, -4F, 6, 7, 7);
        head.setRotationPoint(0.5F, -1.5F, 1F);
        head.setTextureSize(64, 32);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        neck = new ModelRenderer(this, 0, 37);
        neck.addBox(-2F, 0F, -2F, 4, 2, 4);
        neck.setRotationPoint(0.5F, -3F, 1F);
        neck.setTextureSize(64, 32);
        neck.mirror = true;
        setRotation(neck, 0F, 0F, 0F);
        body1 = new ModelRenderer(this, 0, 0);
        body1.addBox(-4F, 0F, -4F, 9, 10, 8);
        body1.setRotationPoint(0F, -1.5F, 1F);
        body1.setTextureSize(64, 32);
        body1.mirror = true;
        setRotation(body1, 0F, 0F, 0F);
        body2 = new ModelRenderer(this, 0, 19);
        body2.addBox(-4F, 0F, -5F, 11, 7, 10);
        body2.setRotationPoint(-1F, -1F, 1F);
        body2.setTextureSize(64, 32);
        body2.mirror = true;
        setRotation(body2, 0F, 0F, 0F);
        body3 = new ModelRenderer(this, 0, 44);
        body3.addBox(-4F, 0F, -2F, 6, 10, 5);
        body3.setRotationPoint(1.5F, 3.5F, 2F);
        body3.setTextureSize(64, 32);
        body3.mirror = true;
        setRotation(body3, -0.2094395F, 0F, 0F);
        armjointleft = new ModelRenderer(this, 17, 38);
        armjointleft.addBox(-1F, -1F, -1F, 1, 2, 2);
        armjointleft.setRotationPoint(7F, 1.5F, 1F);
        armjointleft.setTextureSize(64, 32);
        armjointleft.mirror = true;
        setRotation(armjointleft, 0F, 0F, 0F);
        armjointright = new ModelRenderer(this, 17, 38);
        armjointright.addBox(0F, -1F, -1F, 1, 2, 2);
        armjointright.setRotationPoint(-6F, 1.5F, 1F);
        armjointright.setTextureSize(64, 32);
        armjointright.mirror = true;
        setRotation(armjointright, 0F, 0F, 0F);
        armleft = new ModelRenderer(this, 63, 0);
        armleft.addBox(0F, -2F, -1.5F, 3, 8, 3);
        armleft.setRotationPoint(7F, 1.5F, 1F);
        armleft.setTextureSize(64, 32);
        armleft.mirror = true;
        setRotation(armleft, 0F, 0F, 0F);
        armright = new ModelRenderer(this, 63, 0);
        armright.addBox(-3F, -2F, -1.5F, 3, 8, 3);
        armright.setRotationPoint(-6F, 1.5F, 1F);
        armright.setTextureSize(64, 32);
        armright.mirror = true;
        setRotation(armright, 0F, 0F, 0F);
        armhandright = new ModelRenderer(this, 43, 19);
        armhandright.addBox(-2F, 0F, -2F, 4, 8, 4);
        armhandright.setRotationPoint(-7.5F, 6.5F, 1F);
        armhandright.setTextureSize(64, 32);
        armhandright.mirror = true;
        setRotation(armhandright, -0.5585054F, 0F, 0F);
        armhandleft = new ModelRenderer(this, 43, 19);
        armhandleft.addBox(-2F, 0F, -2F, 4, 8, 4);
        armhandleft.setRotationPoint(8.5F, 6.5F, 1F);
        armhandleft.setTextureSize(64, 32);
        armhandleft.mirror = true;
        setRotation(armhandleft, -0.5585054F, 0F, 0F);
        hover1 = new ModelRenderer(this, 61, 36);
        hover1.addBox(-4F, 0F, -4F, 9, 2, 7);
        hover1.setRotationPoint(0F, 12.5F, 1F);
        hover1.setTextureSize(64, 32);
        hover1.mirror = true;
        setRotation(hover1, 0F, 0F, 0F);
        hover2 = new ModelRenderer(this, 24, 38);
        hover2.addBox(-4.5F, 0F, -4F, 10, 5, 8);
        hover2.setRotationPoint(0F, 13F, 0.5F);
        hover2.setTextureSize(64, 32);
        hover2.mirror = true;
        setRotation(hover2, 0F, 0F, 0F);
        hover3 = new ModelRenderer(this, 61, 46);
        hover3.addBox(-4F, 0F, -4F, 9, 2, 7);
        hover3.setRotationPoint(0F, 16.5F, 1F);
        hover3.setTextureSize(64, 32);
        hover3.mirror = true;
        setRotation(hover3, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        head.render(f5);
        neck.render(f5);
        body1.render(f5);
        body2.render(f5);
        body3.render(f5);
        armjointleft.render(f5);
        armjointright.render(f5);
        armleft.render(f5);
        armright.render(f5);
        armhandright.render(f5);
        armhandleft.render(f5);
        hover1.render(f5);
        hover2.render(f5);
        hover3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
